<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Practica1RME">
      <HintPath>..\..\..\..\..\Documents\TDP1\Practica1RME\bin\Debug\net8.0\Practica1RME.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
